# 服务端口
server:
  port: 8206
  # 服务名
spring:
  application:
    name: service-order
  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.108.85.19:3306/yygh_order?characterEncoding=utf-8&useSSL=false
    username: root
    password: liermysql

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  data:
    mongodb:
      uri: mongodb://47.108.85.19:27017/yygh_hosp

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #rabbitmq地址
  rabbitmq:
    host: 47.108.85.19
    port: 5672
    username: admin
    password: 123
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

#指定mapper文件目录
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml



#关联的公众号appid
weixin:
    appid: wx74862e0dfcf69954
  #商户号
    partner: 1558950191
  #商户key
    partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  #支付退款证书
    cert: E:\\yygh\\service\\service-order\\src\\main\\resources\\cert\\apiclient_cert.p12
