# 服务端口
server:
  port: 8160
  # 服务名
spring:
  application:
    name: service-user

  #redis
  redis:
    host: 47.108.85.19
    port: 6379
    database: 0
    timeout: 1800000
    lettuce.pool.max-active: 20
    lettuce.pool.max-wait: -1
    #最大阻塞等待时间(负数表示没限制)
    lettuce.pool.max-idle: 5
    lettuce.pool.min-idle: 0

  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.108.85.19:3306/yygh_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: liermysql

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

#微信登录相关数据
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
#前端调用地址
yygh:
  baseUrl: http://localhost:3000
