# 服务端口
server:
  port: 8202
  # 服务名
spring:
  application:
    name: service-dict
  redis:
    host: 47.108.85.19
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
  data:
    mongodb:
      uri: mongodb://47.108.85.19:27017/yygh_hosp
      auto-index-creation: false

  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.108.85.19:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
    username: root
    password: liermysql

    # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #设置sentinel地址
  #    sentinel:
  #      transport:
  #        dashboard: localhost:8080
  #        port: 8719

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

    #mongodb地址
    #  data:
    #    mongodb:
    #      host: 192.168.44.163
    #      port: 27017
    #      database: yygh_hosp

    #rabbitmq地址
  #  rabbitmq:
  #    host: 192.168.100.130
  #    port: 5672
  #    password: admin
  #    username: 123

  #配置mapper xml文件的路径
  #mybatis-plus.mapper-locations=classpath:com/atguigu/yygh/mapper/xml/*.xml
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


  #开启sentinel
#feign:
#  sentinel:
#    enabled: true

#控制台打印日志级别
#logging:
#  level:
#    root: debug


